/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function isPointOnLineFast(encodedPolyline: string, pLat: number, pLon: number, margin: number): boolean

export declare function plus100(input: number): number
